# Temporary hardcoded toolchain paths
set(CMAKE_SYSTEM_NAME None)
set(CMAKE_SYSTEM_PROCESSOR i686)

set(ASOS_TARGET "${CMAKE_SYSTEM_PROCESSOR}-elf")

set(CMAKE_ASM_COMPILER "${ASOS_TOOLCHAIN_DIR}/bin/${ASOS_TARGET}-as")
set(CMAKE_C_COMPILER "${ASOS_TOOLCHAIN_DIR}/bin/${ASOS_TARGET}-gcc")
set(CMAKE_CXX_COMPILER "${ASOS_TOOLCHAIN_DIR}/bin/${ASOS_TARGET}-g++")
set(CMAKE_LINKER "${ASOS_TOOLCHAIN_DIR}/bin/${ASOS_TARGET}-ld")

set(CMAKE_ASM_LINK_EXECUTABLE "<CMAKE_LINKER> <LINK_FLAGS> <OBJECTS> -o <TARGET>")

